version: '3.8'

networks:
  internal:

services:
  db:
    restart: always
    image: postgres:alpine
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=course
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    command: postgres -c 'shared_preload_libraries='
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d course"]
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    restart: always
    image: redis:latest
    ports:
      - 6380:6379
    environment:
      - HOST_REDIS=cache
      - PORT_REDIS=6380
  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper
    expose:
    - "2181"
    ports:
    - "2181:2181"
    networks:
      - internal
  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:5.2.2
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - internal