version: '3.8'

networks:
  internal:
    driver: bridge

services:
  courses-services:
    build: ./
    command: ./courses-services
    restart: always
    networks:
      - internal
    ports:
      - 8080:8080
    depends_on:
      - db
      - cache
    environment:
      - DSN_COURSES=postgresql://root:secret@db:5432/course?sslmode=disable
      - DRIVER=postgres
      - HOST_REDIS=cache
      - PORT_REDIS=6379

  db:
    restart: always
    image: postgres:alpine
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
    networks:
      - internal
    ports:
      - 5434:5435
    environment:
      - POSTGRES_DB=course
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    command: postgres -c 'shared_preload_libraries='
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d course"]
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    restart: always
    image: redis:alpine
    volumes: 
      - ./pkg/cache
    networks:
      - internal
    ports:
      - 6379:6379
    environment:
      - HOST_REDIS=cache
      - PORT_REDIS=6379
    

